Description: >
  Felix Lutze / Capstone Project
  Creates two individual hosts to manage the EKS-Cluster

Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Default: capstone-project
    Type: String
  SSHKeyName:
    Description: SSH key for management access
    Default: udacity
    Type: String
  amiImageId:
    Description: Defines the Image-ID of the OS to deploy
    Default: ami-0715c1897453cabd1
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-management-SG
      GroupDescription: Allow port 22 for management
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Resources:
  Bastion1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: !Ref amiImageId
      NetworkInterfaces:
        - GroupSet:
            - Fn::ImportValue: !Ref InstanceSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId:
            Fn::ImportValue: !Sub '${EnvironmentName}-PUB1-SN'
      KeyName: !Ref SSHKeyName
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-management1
        - Key: Project
          Value: !Ref EnvironmentName

  Bastion2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: !Ref amiImageId
      NetworkInterfaces:
        - GroupSet:
            - Fn::ImportValue: !Ref InstanceSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId:
            Fn::ImportValue: !Sub '${EnvironmentName}-PUB2-SN'
      KeyName: !Ref SSHKeyName
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-management2
        - Key: Project
          Value: !Ref EnvironmentName
