- name: Copy deployment configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-deployment.yaml"
    dest: $HOME

- name: Apply deployment configuration
  shell: "/usr/local/bin/kubectl apply -f capstone-project-deployment.yaml"
  args:
    chdir: $HOME
