---
- name: "Configure the EKS cluster with kubectl"
  hosts: management[0]
  remote_user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  roles:
    - capstone-deployment
    - capstone-service
